name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ["12.0.1"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "21"
          java-package: jdk
          architecture: x64
      - uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.5
          arguments: test --info -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}


